name: FollowTyler
favicon: null
layout_spectrum: 0.22988117206841707
typography_spectrum: 0.05057027982547879
title: 'Follow Tyler!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#65666c'
    - '#708db5'
    - '#d5a895'
    - '#7a432a'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
